stages:
  - test

include:
  - project: Northern.tech/Mender/mendertesting
    file:
      - qa-common/runner.yml
      - qa-common/retry.yml
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-commits.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-license.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-python3-format.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-github-status-updates.yml'

test:check-version-bump:
  stage: test
  image: registry.gitlab.com/northern.tech/mender/mender-test-containers/base-ubuntu:master
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - python3 -m venv .venv
    - source .venv/bin/activate
    - pip3 install pytest
  script:
    - pytest -v -rs -s tests/version/test_version_bump.py

default:
  tags: !reference [.qa-common-default-runner, tags]
  retry: !reference [.qa-common-default-retry, retry]

variables:
  LICENSE_HEADERS_IGNORE_FILES_REGEXP: '\./meta-mender-core/recipes-bsp/u-boot/files/.*\.py\|\./meta-mender-core/recipes-bsp/systemd-mender-config/files/ab_setup\.py'
