stages:
  - test

include:
  - project: Northern.tech/Mender/mendertesting
    file:
      - qa-common/runner.yml
      - qa-common/retry.yml
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-commits.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-license.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-check-python3-format.yml'
  - project: 'Northern.tech/Mender/mendertesting'
    file: '.gitlab-ci-github-status-updates.yml'

.python-env:
  image: python:3.11-slim
  before_script:
    - apt-get update && apt-get install -y git
    - pip install pytest

check-version-bump:
  extends: .python-env
  stage: test
  script:
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - pytest -v -c /dev/null tests/acceptance/test_backport.py

default:
  tags: !reference [.qa-common-default-runner, tags]
  retry: !reference [.qa-common-default-retry, retry]

variables:
  LICENSE_HEADERS_IGNORE_FILES_REGEXP: '\./meta-mender-core/recipes-bsp/u-boot/files/.*\.py\|\./meta-mender-core/recipes-bsp/systemd-mender-config/files/ab_setup\.py'
