#!/bin/bash
set -e

SOURCE_DIR=${SOURCE_DIR:-/tmp}
IMAGE_FILE=${IMAGE_FILE:-core-image-full-cmdline-raspberrypi3.sdimg}
TARGET_DEV=${TARGET_DEV:-/dev/mmcblk0}

IMAGE_SOURCE_FILE=${SOURCE_DIR}/${IMAGE_FILE}

# unmount all partitions from target dev
for mp in $(cat /proc/mounts |grep "$TARGET_DEV" | cut -d' ' -f2); do
    echo "unmounting $mp (mounted from $TARGET_DEV)"
    umount $mp
done

if [ -e "$IMAGE_SOURCE_FILE" ]; then
    echo "writing system image $IMAGE_FILE to $TARGET_DEV"
    dd if=$IMAGE_SOURCE_FILE of=$TARGET_DEV bs=1M
else
    echo "no system image to deploy"
fi
