TMP ?= /tmp
LOGS ?= test_uboot_compile-logs
MAYBE_UBI ?=

# BOARD_LOGS should be set already by the test.
all: $(BOARD_LOGS)

clean:
	rm -rf $(LOGS)

$(LOGS):
	mkdir -p $(LOGS)

$(BOARD_LOGS): $(LOGS)

# Do the auto configuration for each board and make a log. Failure is not
# recorded in the return code, but in the log instead.
$(LOGS)/%_defconfig:
	echo "Starting `basename $@` compile test at `date`"
	if [ -z "$(TESTS_DIR)" -o -z "$(UBOOT_SRC)" ]; then \
		echo "Not all variables are set"; \
		exit 1; \
	fi
	rm -rf "$(TMP)/`basename $@`"
	mkdir -p "$(TMP)/`basename $@`"
	cp -r "$(UBOOT_SRC)" "$(TMP)/`basename $@`/orig"
	mkdir -p "$(TMP)/`basename $@`/work"

	# Auto configure board.
	$(TESTS_DIR)/../../meta-mender-core/recipes-bsp/u-boot/files/uboot_auto_configure.sh \
			--config=`basename $@` \
			--src-dir="$(TMP)/`basename $@`/orig" \
			--tmp-dir="$(TMP)/`basename $@`/work" \
			--kconfig-fragment="$(TMP)/`basename $@`/orig/mender_Kconfig_fragment" \
			$(MAYBE_UBI) \
			--debug \
			>> $@ 2>&1 \
		|| ( echo AutoPatchFailed >> $@ )

	# Setup compile.
	$(MAKE) $(SUBJOBCOUNT) -C "$(TMP)/`basename $@`/orig" "`basename $@`" \
			>> $@ 2>&1 \
		|| ( echo AutoPatchFailed >> $@ )

	# Try to compile it.
	$(MAKE) $(SUBJOBCOUNT) -C "$(TMP)/`basename $@`/orig" \
			>> $@ 2>&1 \
		|| ( echo AutoPatchFailed >> $@ )

	rm -rf "$(TMP)/`basename $@`"

	echo "Finished `basename $@` compile test at `date`"
