#!/bin/sh

# usage:
#  mender-qemu [<image-name>]
#  mender-qemu core-image-minimal
#
# if image name is not provided, the script will attempt to run
# core-image-full-cmdline
#

# NOTE: current settings forward
#           ssh: port 8822
#           VNC: port 5923
#           serial console: stdio

set -e
set -x

# if called under Yocto/OE shell, BUILDDIR will already be set correctly
if [ -z "$BUILDDIR" ]; then
    # try to guess BUILDDIR
    BUILDDIR="`dirname $0`"/../../build
fi

IMAGE_NAME=$1
# check if it's named like an image
if [ -n "$IMAGE_NAME" ] && echo "$IMAGE_NAME" | grep "image" >/dev/null 2>&1; then
    # IMAGE name was passed in command line, skip the argument
    shift
else
    IMAGE_NAME=core-image-full-cmdline
fi

if [ -d ${BUILDDIR}/tmp ]; then
    BUILDTMP=${BUILDDIR}/tmp
else
    BUILDTMP=${BUILDDIR}/tmp-glibc
fi

MACHINE=${MACHINE:-"vexpress-qemu"}
UBOOT_ELF=${UBOOT_ELF:-"${BUILDTMP}/deploy/images/${MACHINE}/u-boot.elf"}
VEXPRESS_IMG=${VEXPRESS_IMG:-"${BUILDTMP}/deploy/images/${MACHINE}/${IMAGE_NAME}-${MACHINE}.sdimg"}
QEMU_SYSTEM_ARM=${QEMU_SYSTEM_ARM:-"qemu-system-arm"}
RANDOM_MAC="52:54:00$(od -txC -An -N3 /dev/urandom|tr \  :)"
# use to pass -drive .. parameters directly
QEMU_DRIVE=${QEMU_DRIVE:-""}

QEMU_ARGS=""
case $VEXPRESS_IMG in
    *.sdimg)
        QEMU_ARGS="$QEMU_ARGS -drive file=$VEXPRESS_IMG,if=sd "
        ;;
    *.vexpress-nor)
        tar -C /tmp -xvf $VEXPRESS_IMG
        QEMU_ARGS="$QEMU_ARGS -drive file=/tmp/nor0,if=pflash,format=raw -drive file=/tmp/nor1,if=pflash,format=raw "
        ;;
    *)
        if [ -n "$QEMU_DRIVE" ]; then
            QEMU_ARGS="$QEMU_ARGS $QEMU_DRIVE "
        else
            echo "unsupported image $VEXPRESS_IMG"
            exit 1
        fi
esac

QEMU_AUDIO_DRV=none \
    exec $QEMU_SYSTEM_ARM \
    -M vexpress-a9 \
    -m 128M \
    -kernel "$UBOOT_ELF" \
    -net nic,macaddr="$RANDOM_MAC" \
    -net user,hostfwd=tcp::8822-:22 \
    -display vnc=:23 \
    -nographic \
    $QEMU_ARGS \
    "$@"
