#!/bin/bash
set -e -x
MOUNT_DEV=${MOUNT_DEV:-/dev/mmcblk0p1}
if [ -d /uboot ]; then
    MOUNTPOINT=/uboot
else
    MOUNTPOINT=/mnt
fi

case "$1" in
    status)
        if grep "mender" $MOUNTPOINT/boot.scr > /dev/null; then
            echo "test image is enabled"
        else
            echo "test image is disabled"
        fi
        ;;
    off)
        if grep "mender" $MOUNTPOINT/boot.scr > /dev/null; then
            echo "deactivating test image"
            cp $MOUNTPOINT/boot.scr $MOUNTPOINT/boot-mender.scr
            cp $MOUNTPOINT/boot-for-flashing.scr $MOUNTPOINT/boot.scr
            sed -ie 's,root=${mender_kernel_root},root=/dev/sda2,' $MOUNTPOINT/cmdline.txt
        else
            echo "test-image not running"
            exit 1
        fi
        ;;
    on|'')
        echo "activating test image"
        mount $MOUNT_DEV $MOUNTPOINT
        if [ -f $MOUNTPOINT/boot-mender.scr ]; then
            cp $MOUNTPOINT/boot-mender.scr $MOUNTPOINT/boot.scr
        fi
        sed -ie 's,root=/dev/sda2,root=${mender_kernel_root},' $MOUNTPOINT/cmdline.txt
        umount $MOUNT_DEV
        ;;
esac
