#!/bin/sh

# NOTE: current settings forward
#           ssh: port 8822
#           VNC: port 5923
#           serial console: stdio

set -e
set -x

BUILDDIR="`dirname $0`"/../../build

QEMU_AUDIO_DRV=none \
    ${BUILDDIR}/tmp/sysroots/x86_64-linux/usr/bin/qemu-system-arm \
    -M vexpress-a9 \
    -m 1G \
    -kernel ${BUILDDIR}/tmp/deploy/images/vexpress-qemu/u-boot.elf \
    -drive file=${BUILDDIR}/tmp/deploy/images/vexpress-qemu/core-image-full-cmdline-vexpress-qemu.sdimg,if=sd,format=raw \
    -net nic \
    -net user,hostfwd=tcp::8822-:22 \
    -display vnc=:23 \
    -serial stdio \
    "$@"
